/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as maintenanceRouteImport } from './app/maintenance'
import { Route as authLayoutRouteImport } from './app/auth/layout'
import { Route as adminDotrouteRouteImport } from './app/admin.route'
import { Route as indexRouteImport } from './app/index'
import { Route as profilePagesIndexRouteImport } from './app/profile/pages/index'
import { Route as authPagesResetPasswordRouteImport } from './app/auth/pages/reset-password'
import { Route as authPagesLoginRouteImport } from './app/auth/pages/login'
import { Route as authPagesForgotPasswordRouteImport } from './app/auth/pages/forgot-password'
import { Route as ApiMediaRouteImport } from './app/api/media'
import { Route as usersLayoutRouteImport } from './app/users/layout'
import { Route as storiesLayoutRouteImport } from './app/stories/layout'
import { Route as dashboardPagesAdminDashboardRouteImport } from './app/dashboard/pages/admin-dashboard'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$'
import { Route as usersPagesCreateRouteImport } from './app/users/pages/create'
import { Route as storiesPagesCreateRouteImport } from './app/stories/pages/create'
import { Route as usersPagesListRouteImport } from './app/users/pages/list'
import { Route as storiesPagesListRouteImport } from './app/stories/pages/list'
import { Route as ApiAuthAdminSplatRouteImport } from './app/api/auth/admin/$'
import { Route as usersPagesUserIdEditRouteImport } from './app/users/pages/userId-edit'
import { Route as storiesPagesEditRouteImport } from './app/stories/pages/edit'

const maintenanceRoute = maintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const adminDotrouteRoute = adminDotrouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const profilePagesIndexRoute = profilePagesIndexRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => adminDotrouteRoute,
} as any)
const authPagesResetPasswordRoute = authPagesResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authLayoutRoute,
} as any)
const authPagesLoginRoute = authPagesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authLayoutRoute,
} as any)
const authPagesForgotPasswordRoute = authPagesForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authLayoutRoute,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const usersLayoutRoute = usersLayoutRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => adminDotrouteRoute,
} as any)
const storiesLayoutRoute = storiesLayoutRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => adminDotrouteRoute,
} as any)
const dashboardPagesAdminDashboardRoute =
  dashboardPagesAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => adminDotrouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const usersPagesCreateRoute = usersPagesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => usersLayoutRoute,
} as any)
const storiesPagesCreateRoute = storiesPagesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => storiesLayoutRoute,
} as any)
const usersPagesListRoute = usersPagesListRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => usersLayoutRoute,
} as any)
const storiesPagesListRoute = storiesPagesListRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => storiesLayoutRoute,
} as any)
const ApiAuthAdminSplatRoute = ApiAuthAdminSplatRouteImport.update({
  id: '/api/auth/admin/$',
  path: '/api/auth/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const usersPagesUserIdEditRoute = usersPagesUserIdEditRouteImport.update({
  id: '/$userId/edit',
  path: '/$userId/edit',
  getParentRoute: () => usersLayoutRoute,
} as any)
const storiesPagesEditRoute = storiesPagesEditRouteImport.update({
  id: '/$storyId/edit',
  path: '/$storyId/edit',
  getParentRoute: () => storiesLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof indexRoute
  '/admin': typeof adminDotrouteRouteWithChildren
  '/auth': typeof authLayoutRouteWithChildren
  '/maintenance': typeof maintenanceRoute
  '/admin/dashboard': typeof dashboardPagesAdminDashboardRoute
  '/admin/stories': typeof storiesLayoutRouteWithChildren
  '/admin/users': typeof usersLayoutRouteWithChildren
  '/api/media': typeof ApiMediaRoute
  '/auth/forgot-password': typeof authPagesForgotPasswordRoute
  '/auth/login': typeof authPagesLoginRoute
  '/auth/reset-password': typeof authPagesResetPasswordRoute
  '/admin/profile': typeof profilePagesIndexRoute
  '/admin/stories/': typeof storiesPagesListRoute
  '/admin/users/': typeof usersPagesListRoute
  '/admin/stories/create': typeof storiesPagesCreateRoute
  '/admin/users/create': typeof usersPagesCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/stories/$storyId/edit': typeof storiesPagesEditRoute
  '/admin/users/$userId/edit': typeof usersPagesUserIdEditRoute
  '/api/auth/admin/$': typeof ApiAuthAdminSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof indexRoute
  '/admin': typeof adminDotrouteRouteWithChildren
  '/auth': typeof authLayoutRouteWithChildren
  '/maintenance': typeof maintenanceRoute
  '/admin/dashboard': typeof dashboardPagesAdminDashboardRoute
  '/api/media': typeof ApiMediaRoute
  '/auth/forgot-password': typeof authPagesForgotPasswordRoute
  '/auth/login': typeof authPagesLoginRoute
  '/auth/reset-password': typeof authPagesResetPasswordRoute
  '/admin/profile': typeof profilePagesIndexRoute
  '/admin/stories': typeof storiesPagesListRoute
  '/admin/users': typeof usersPagesListRoute
  '/admin/stories/create': typeof storiesPagesCreateRoute
  '/admin/users/create': typeof usersPagesCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/stories/$storyId/edit': typeof storiesPagesEditRoute
  '/admin/users/$userId/edit': typeof usersPagesUserIdEditRoute
  '/api/auth/admin/$': typeof ApiAuthAdminSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof indexRoute
  '/admin': typeof adminDotrouteRouteWithChildren
  '/auth': typeof authLayoutRouteWithChildren
  '/maintenance': typeof maintenanceRoute
  '/admin/dashboard': typeof dashboardPagesAdminDashboardRoute
  '/admin/stories': typeof storiesLayoutRouteWithChildren
  '/admin/users': typeof usersLayoutRouteWithChildren
  '/api/media': typeof ApiMediaRoute
  '/auth/forgot-password': typeof authPagesForgotPasswordRoute
  '/auth/login': typeof authPagesLoginRoute
  '/auth/reset-password': typeof authPagesResetPasswordRoute
  '/admin/profile': typeof profilePagesIndexRoute
  '/admin/stories/': typeof storiesPagesListRoute
  '/admin/users/': typeof usersPagesListRoute
  '/admin/stories/create': typeof storiesPagesCreateRoute
  '/admin/users/create': typeof usersPagesCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/stories/$storyId/edit': typeof storiesPagesEditRoute
  '/admin/users/$userId/edit': typeof usersPagesUserIdEditRoute
  '/api/auth/admin/$': typeof ApiAuthAdminSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/maintenance'
    | '/admin/dashboard'
    | '/admin/stories'
    | '/admin/users'
    | '/api/media'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/admin/profile'
    | '/admin/stories/'
    | '/admin/users/'
    | '/admin/stories/create'
    | '/admin/users/create'
    | '/api/auth/$'
    | '/admin/stories/$storyId/edit'
    | '/admin/users/$userId/edit'
    | '/api/auth/admin/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/maintenance'
    | '/admin/dashboard'
    | '/api/media'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/admin/profile'
    | '/admin/stories'
    | '/admin/users'
    | '/admin/stories/create'
    | '/admin/users/create'
    | '/api/auth/$'
    | '/admin/stories/$storyId/edit'
    | '/admin/users/$userId/edit'
    | '/api/auth/admin/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/maintenance'
    | '/admin/dashboard'
    | '/admin/stories'
    | '/admin/users'
    | '/api/media'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/admin/profile'
    | '/admin/stories/'
    | '/admin/users/'
    | '/admin/stories/create'
    | '/admin/users/create'
    | '/api/auth/$'
    | '/admin/stories/$storyId/edit'
    | '/admin/users/$userId/edit'
    | '/api/auth/admin/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute
  adminDotrouteRoute: typeof adminDotrouteRouteWithChildren
  authLayoutRoute: typeof authLayoutRouteWithChildren
  maintenanceRoute: typeof maintenanceRoute
  ApiMediaRoute: typeof ApiMediaRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthAdminSplatRoute: typeof ApiAuthAdminSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof maintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof adminDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof profilePagesIndexRouteImport
      parentRoute: typeof adminDotrouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof authPagesResetPasswordRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof authPagesLoginRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof authPagesForgotPasswordRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof usersLayoutRouteImport
      parentRoute: typeof adminDotrouteRoute
    }
    '/admin/stories': {
      id: '/admin/stories'
      path: '/stories'
      fullPath: '/admin/stories'
      preLoaderRoute: typeof storiesLayoutRouteImport
      parentRoute: typeof adminDotrouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof dashboardPagesAdminDashboardRouteImport
      parentRoute: typeof adminDotrouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/create': {
      id: '/admin/users/create'
      path: '/create'
      fullPath: '/admin/users/create'
      preLoaderRoute: typeof usersPagesCreateRouteImport
      parentRoute: typeof usersLayoutRoute
    }
    '/admin/stories/create': {
      id: '/admin/stories/create'
      path: '/create'
      fullPath: '/admin/stories/create'
      preLoaderRoute: typeof storiesPagesCreateRouteImport
      parentRoute: typeof storiesLayoutRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof usersPagesListRouteImport
      parentRoute: typeof usersLayoutRoute
    }
    '/admin/stories/': {
      id: '/admin/stories/'
      path: '/'
      fullPath: '/admin/stories/'
      preLoaderRoute: typeof storiesPagesListRouteImport
      parentRoute: typeof storiesLayoutRoute
    }
    '/api/auth/admin/$': {
      id: '/api/auth/admin/$'
      path: '/api/auth/admin/$'
      fullPath: '/api/auth/admin/$'
      preLoaderRoute: typeof ApiAuthAdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId/edit': {
      id: '/admin/users/$userId/edit'
      path: '/$userId/edit'
      fullPath: '/admin/users/$userId/edit'
      preLoaderRoute: typeof usersPagesUserIdEditRouteImport
      parentRoute: typeof usersLayoutRoute
    }
    '/admin/stories/$storyId/edit': {
      id: '/admin/stories/$storyId/edit'
      path: '/$storyId/edit'
      fullPath: '/admin/stories/$storyId/edit'
      preLoaderRoute: typeof storiesPagesEditRouteImport
      parentRoute: typeof storiesLayoutRoute
    }
  }
}

interface storiesLayoutRouteChildren {
  storiesPagesListRoute: typeof storiesPagesListRoute
  storiesPagesCreateRoute: typeof storiesPagesCreateRoute
  storiesPagesEditRoute: typeof storiesPagesEditRoute
}

const storiesLayoutRouteChildren: storiesLayoutRouteChildren = {
  storiesPagesListRoute: storiesPagesListRoute,
  storiesPagesCreateRoute: storiesPagesCreateRoute,
  storiesPagesEditRoute: storiesPagesEditRoute,
}

const storiesLayoutRouteWithChildren = storiesLayoutRoute._addFileChildren(
  storiesLayoutRouteChildren,
)

interface usersLayoutRouteChildren {
  usersPagesListRoute: typeof usersPagesListRoute
  usersPagesCreateRoute: typeof usersPagesCreateRoute
  usersPagesUserIdEditRoute: typeof usersPagesUserIdEditRoute
}

const usersLayoutRouteChildren: usersLayoutRouteChildren = {
  usersPagesListRoute: usersPagesListRoute,
  usersPagesCreateRoute: usersPagesCreateRoute,
  usersPagesUserIdEditRoute: usersPagesUserIdEditRoute,
}

const usersLayoutRouteWithChildren = usersLayoutRoute._addFileChildren(
  usersLayoutRouteChildren,
)

interface adminDotrouteRouteChildren {
  dashboardPagesAdminDashboardRoute: typeof dashboardPagesAdminDashboardRoute
  storiesLayoutRoute: typeof storiesLayoutRouteWithChildren
  usersLayoutRoute: typeof usersLayoutRouteWithChildren
  profilePagesIndexRoute: typeof profilePagesIndexRoute
}

const adminDotrouteRouteChildren: adminDotrouteRouteChildren = {
  dashboardPagesAdminDashboardRoute: dashboardPagesAdminDashboardRoute,
  storiesLayoutRoute: storiesLayoutRouteWithChildren,
  usersLayoutRoute: usersLayoutRouteWithChildren,
  profilePagesIndexRoute: profilePagesIndexRoute,
}

const adminDotrouteRouteWithChildren = adminDotrouteRoute._addFileChildren(
  adminDotrouteRouteChildren,
)

interface authLayoutRouteChildren {
  authPagesForgotPasswordRoute: typeof authPagesForgotPasswordRoute
  authPagesLoginRoute: typeof authPagesLoginRoute
  authPagesResetPasswordRoute: typeof authPagesResetPasswordRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authPagesForgotPasswordRoute: authPagesForgotPasswordRoute,
  authPagesLoginRoute: authPagesLoginRoute,
  authPagesResetPasswordRoute: authPagesResetPasswordRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  adminDotrouteRoute: adminDotrouteRouteWithChildren,
  authLayoutRoute: authLayoutRouteWithChildren,
  maintenanceRoute: maintenanceRoute,
  ApiMediaRoute: ApiMediaRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthAdminSplatRoute: ApiAuthAdminSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
