/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as maintenanceRouteImport } from './app/maintenance'
import { Route as authLayoutRouteImport } from './app/auth/layout'
import { Route as adminDotrouteRouteImport } from './app/admin.route'
import { Route as indexRouteImport } from './app/index'
import { Route as profilePagesIndexRouteImport } from './app/profile/pages/index'
import { Route as importPagesIndexRouteImport } from './app/import/pages/index'
import { Route as authPagesResetPasswordRouteImport } from './app/auth/pages/reset-password'
import { Route as authPagesLoginRouteImport } from './app/auth/pages/login'
import { Route as authPagesForgotPasswordRouteImport } from './app/auth/pages/forgot-password'
import { Route as ApiMediaRouteImport } from './app/api/media'
import { Route as usersLayoutRouteImport } from './app/users/layout'
import { Route as storiesLayoutRouteImport } from './app/stories/layout'
import { Route as researchLayoutRouteImport } from './app/research/layout'
import { Route as programsLayoutRouteImport } from './app/programs/layout'
import { Route as opportunitiesLayoutRouteImport } from './app/opportunities/layout'
import { Route as newsLayoutRouteImport } from './app/news/layout'
import { Route as membersLayoutRouteImport } from './app/members/layout'
import { Route as eventsLayoutRouteImport } from './app/events/layout'
import { Route as dashboardPagesAdminDashboardRouteImport } from './app/dashboard/pages/admin-dashboard'
import { Route as ApiStoriesSplatRouteImport } from './app/api/stories/$'
import { Route as ApiStatsSplatRouteImport } from './app/api/stats/$'
import { Route as ApiResearchSplatRouteImport } from './app/api/research/$'
import { Route as ApiProgramsSplatRouteImport } from './app/api/programs/$'
import { Route as ApiOpportunitiesSplatRouteImport } from './app/api/opportunities/$'
import { Route as ApiNewsSplatRouteImport } from './app/api/news/$'
import { Route as ApiEventsSplatRouteImport } from './app/api/events/$'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$'
import { Route as ApiAdminImportExcelRouteImport } from './app/api/admin/import-excel'
import { Route as usersPagesCreateRouteImport } from './app/users/pages/create'
import { Route as storiesPagesCreateRouteImport } from './app/stories/pages/create'
import { Route as researchPagesCreateRouteImport } from './app/research/pages/create'
import { Route as programsPagesCreateRouteImport } from './app/programs/pages/create'
import { Route as opportunitiesPagesCreateRouteImport } from './app/opportunities/pages/create'
import { Route as newsPagesCreateRouteImport } from './app/news/pages/create'
import { Route as membersPagesCreateRouteImport } from './app/members/pages/create'
import { Route as eventsPagesCreateRouteImport } from './app/events/pages/create'
import { Route as eventsPagesEventIdIndexRouteImport } from './app/events/pages/$eventId-index'
import { Route as usersPagesListRouteImport } from './app/users/pages/list'
import { Route as storiesPagesListRouteImport } from './app/stories/pages/list'
import { Route as researchPagesListRouteImport } from './app/research/pages/list'
import { Route as programsPagesListRouteImport } from './app/programs/pages/list'
import { Route as opportunitiesPagesListRouteImport } from './app/opportunities/pages/list'
import { Route as newsPagesListRouteImport } from './app/news/pages/list'
import { Route as membersPagesListRouteImport } from './app/members/pages/list'
import { Route as eventsPagesListRouteImport } from './app/events/pages/list'
import { Route as ApiAuthAdminSplatRouteImport } from './app/api/auth/admin/$'
import { Route as usersPagesUserIdEditRouteImport } from './app/users/pages/userId-edit'
import { Route as storiesPagesEditRouteImport } from './app/stories/pages/edit'
import { Route as researchPagesResearchIdEditRouteImport } from './app/research/pages/$researchId-edit'
import { Route as programsPagesProgramIdEditRouteImport } from './app/programs/pages/programId-edit'
import { Route as opportunitiesPagesEditRouteImport } from './app/opportunities/pages/edit'
import { Route as newsPagesEditRouteImport } from './app/news/pages/edit'
import { Route as membersPagesMemberIdEditRouteImport } from './app/members/pages/memberId-edit'
import { Route as eventsPagesEventIdEditRouteImport } from './app/events/pages/eventId-edit'

const maintenanceRoute = maintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const adminDotrouteRoute = adminDotrouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const profilePagesIndexRoute = profilePagesIndexRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => adminDotrouteRoute,
} as any)
const importPagesIndexRoute = importPagesIndexRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => adminDotrouteRoute,
} as any)
const authPagesResetPasswordRoute = authPagesResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authLayoutRoute,
} as any)
const authPagesLoginRoute = authPagesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authLayoutRoute,
} as any)
const authPagesForgotPasswordRoute = authPagesForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authLayoutRoute,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const usersLayoutRoute = usersLayoutRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => adminDotrouteRoute,
} as any)
const storiesLayoutRoute = storiesLayoutRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => adminDotrouteRoute,
} as any)
const researchLayoutRoute = researchLayoutRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => adminDotrouteRoute,
} as any)
const programsLayoutRoute = programsLayoutRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => adminDotrouteRoute,
} as any)
const opportunitiesLayoutRoute = opportunitiesLayoutRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => adminDotrouteRoute,
} as any)
const newsLayoutRoute = newsLayoutRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => adminDotrouteRoute,
} as any)
const membersLayoutRoute = membersLayoutRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => adminDotrouteRoute,
} as any)
const eventsLayoutRoute = eventsLayoutRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => adminDotrouteRoute,
} as any)
const dashboardPagesAdminDashboardRoute =
  dashboardPagesAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => adminDotrouteRoute,
  } as any)
const ApiStoriesSplatRoute = ApiStoriesSplatRouteImport.update({
  id: '/api/stories/$',
  path: '/api/stories/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsSplatRoute = ApiStatsSplatRouteImport.update({
  id: '/api/stats/$',
  path: '/api/stats/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchSplatRoute = ApiResearchSplatRouteImport.update({
  id: '/api/research/$',
  path: '/api/research/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProgramsSplatRoute = ApiProgramsSplatRouteImport.update({
  id: '/api/programs/$',
  path: '/api/programs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpportunitiesSplatRoute = ApiOpportunitiesSplatRouteImport.update({
  id: '/api/opportunities/$',
  path: '/api/opportunities/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsSplatRoute = ApiNewsSplatRouteImport.update({
  id: '/api/news/$',
  path: '/api/news/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsSplatRoute = ApiEventsSplatRouteImport.update({
  id: '/api/events/$',
  path: '/api/events/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminImportExcelRoute = ApiAdminImportExcelRouteImport.update({
  id: '/api/admin/import-excel',
  path: '/api/admin/import-excel',
  getParentRoute: () => rootRouteImport,
} as any)
const usersPagesCreateRoute = usersPagesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => usersLayoutRoute,
} as any)
const storiesPagesCreateRoute = storiesPagesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => storiesLayoutRoute,
} as any)
const researchPagesCreateRoute = researchPagesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => researchLayoutRoute,
} as any)
const programsPagesCreateRoute = programsPagesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => programsLayoutRoute,
} as any)
const opportunitiesPagesCreateRoute =
  opportunitiesPagesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => opportunitiesLayoutRoute,
  } as any)
const newsPagesCreateRoute = newsPagesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => newsLayoutRoute,
} as any)
const membersPagesCreateRoute = membersPagesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => membersLayoutRoute,
} as any)
const eventsPagesCreateRoute = eventsPagesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => eventsLayoutRoute,
} as any)
const eventsPagesEventIdIndexRoute = eventsPagesEventIdIndexRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => eventsLayoutRoute,
} as any)
const usersPagesListRoute = usersPagesListRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => usersLayoutRoute,
} as any)
const storiesPagesListRoute = storiesPagesListRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => storiesLayoutRoute,
} as any)
const researchPagesListRoute = researchPagesListRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => researchLayoutRoute,
} as any)
const programsPagesListRoute = programsPagesListRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => programsLayoutRoute,
} as any)
const opportunitiesPagesListRoute = opportunitiesPagesListRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => opportunitiesLayoutRoute,
} as any)
const newsPagesListRoute = newsPagesListRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => newsLayoutRoute,
} as any)
const membersPagesListRoute = membersPagesListRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => membersLayoutRoute,
} as any)
const eventsPagesListRoute = eventsPagesListRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => eventsLayoutRoute,
} as any)
const ApiAuthAdminSplatRoute = ApiAuthAdminSplatRouteImport.update({
  id: '/api/auth/admin/$',
  path: '/api/auth/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const usersPagesUserIdEditRoute = usersPagesUserIdEditRouteImport.update({
  id: '/$userId/edit',
  path: '/$userId/edit',
  getParentRoute: () => usersLayoutRoute,
} as any)
const storiesPagesEditRoute = storiesPagesEditRouteImport.update({
  id: '/$storyId/edit',
  path: '/$storyId/edit',
  getParentRoute: () => storiesLayoutRoute,
} as any)
const researchPagesResearchIdEditRoute =
  researchPagesResearchIdEditRouteImport.update({
    id: '/$researchId/edit',
    path: '/$researchId/edit',
    getParentRoute: () => researchLayoutRoute,
  } as any)
const programsPagesProgramIdEditRoute =
  programsPagesProgramIdEditRouteImport.update({
    id: '/$programId/edit',
    path: '/$programId/edit',
    getParentRoute: () => programsLayoutRoute,
  } as any)
const opportunitiesPagesEditRoute = opportunitiesPagesEditRouteImport.update({
  id: '/$opportunityId/edit',
  path: '/$opportunityId/edit',
  getParentRoute: () => opportunitiesLayoutRoute,
} as any)
const newsPagesEditRoute = newsPagesEditRouteImport.update({
  id: '/$newsId/edit',
  path: '/$newsId/edit',
  getParentRoute: () => newsLayoutRoute,
} as any)
const membersPagesMemberIdEditRoute =
  membersPagesMemberIdEditRouteImport.update({
    id: '/$memberId/edit',
    path: '/$memberId/edit',
    getParentRoute: () => membersLayoutRoute,
  } as any)
const eventsPagesEventIdEditRoute = eventsPagesEventIdEditRouteImport.update({
  id: '/$eventId/edit',
  path: '/$eventId/edit',
  getParentRoute: () => eventsLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof indexRoute
  '/admin': typeof adminDotrouteRouteWithChildren
  '/auth': typeof authLayoutRouteWithChildren
  '/maintenance': typeof maintenanceRoute
  '/admin/dashboard': typeof dashboardPagesAdminDashboardRoute
  '/admin/events': typeof eventsLayoutRouteWithChildren
  '/admin/members': typeof membersLayoutRouteWithChildren
  '/admin/news': typeof newsLayoutRouteWithChildren
  '/admin/opportunities': typeof opportunitiesLayoutRouteWithChildren
  '/admin/programs': typeof programsLayoutRouteWithChildren
  '/admin/research': typeof researchLayoutRouteWithChildren
  '/admin/stories': typeof storiesLayoutRouteWithChildren
  '/admin/users': typeof usersLayoutRouteWithChildren
  '/api/media': typeof ApiMediaRoute
  '/auth/forgot-password': typeof authPagesForgotPasswordRoute
  '/auth/login': typeof authPagesLoginRoute
  '/auth/reset-password': typeof authPagesResetPasswordRoute
  '/admin/import': typeof importPagesIndexRoute
  '/admin/profile': typeof profilePagesIndexRoute
  '/admin/events/': typeof eventsPagesListRoute
  '/admin/members/': typeof membersPagesListRoute
  '/admin/news/': typeof newsPagesListRoute
  '/admin/opportunities/': typeof opportunitiesPagesListRoute
  '/admin/programs/': typeof programsPagesListRoute
  '/admin/research/': typeof researchPagesListRoute
  '/admin/stories/': typeof storiesPagesListRoute
  '/admin/users/': typeof usersPagesListRoute
  '/admin/events/$eventId': typeof eventsPagesEventIdIndexRoute
  '/admin/events/create': typeof eventsPagesCreateRoute
  '/admin/members/create': typeof membersPagesCreateRoute
  '/admin/news/create': typeof newsPagesCreateRoute
  '/admin/opportunities/create': typeof opportunitiesPagesCreateRoute
  '/admin/programs/create': typeof programsPagesCreateRoute
  '/admin/research/create': typeof researchPagesCreateRoute
  '/admin/stories/create': typeof storiesPagesCreateRoute
  '/admin/users/create': typeof usersPagesCreateRoute
  '/api/admin/import-excel': typeof ApiAdminImportExcelRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/events/$': typeof ApiEventsSplatRoute
  '/api/news/$': typeof ApiNewsSplatRoute
  '/api/opportunities/$': typeof ApiOpportunitiesSplatRoute
  '/api/programs/$': typeof ApiProgramsSplatRoute
  '/api/research/$': typeof ApiResearchSplatRoute
  '/api/stats/$': typeof ApiStatsSplatRoute
  '/api/stories/$': typeof ApiStoriesSplatRoute
  '/admin/events/$eventId/edit': typeof eventsPagesEventIdEditRoute
  '/admin/members/$memberId/edit': typeof membersPagesMemberIdEditRoute
  '/admin/news/$newsId/edit': typeof newsPagesEditRoute
  '/admin/opportunities/$opportunityId/edit': typeof opportunitiesPagesEditRoute
  '/admin/programs/$programId/edit': typeof programsPagesProgramIdEditRoute
  '/admin/research/$researchId/edit': typeof researchPagesResearchIdEditRoute
  '/admin/stories/$storyId/edit': typeof storiesPagesEditRoute
  '/admin/users/$userId/edit': typeof usersPagesUserIdEditRoute
  '/api/auth/admin/$': typeof ApiAuthAdminSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof indexRoute
  '/admin': typeof adminDotrouteRouteWithChildren
  '/auth': typeof authLayoutRouteWithChildren
  '/maintenance': typeof maintenanceRoute
  '/admin/dashboard': typeof dashboardPagesAdminDashboardRoute
  '/api/media': typeof ApiMediaRoute
  '/auth/forgot-password': typeof authPagesForgotPasswordRoute
  '/auth/login': typeof authPagesLoginRoute
  '/auth/reset-password': typeof authPagesResetPasswordRoute
  '/admin/import': typeof importPagesIndexRoute
  '/admin/profile': typeof profilePagesIndexRoute
  '/admin/events': typeof eventsPagesListRoute
  '/admin/members': typeof membersPagesListRoute
  '/admin/news': typeof newsPagesListRoute
  '/admin/opportunities': typeof opportunitiesPagesListRoute
  '/admin/programs': typeof programsPagesListRoute
  '/admin/research': typeof researchPagesListRoute
  '/admin/stories': typeof storiesPagesListRoute
  '/admin/users': typeof usersPagesListRoute
  '/admin/events/$eventId': typeof eventsPagesEventIdIndexRoute
  '/admin/events/create': typeof eventsPagesCreateRoute
  '/admin/members/create': typeof membersPagesCreateRoute
  '/admin/news/create': typeof newsPagesCreateRoute
  '/admin/opportunities/create': typeof opportunitiesPagesCreateRoute
  '/admin/programs/create': typeof programsPagesCreateRoute
  '/admin/research/create': typeof researchPagesCreateRoute
  '/admin/stories/create': typeof storiesPagesCreateRoute
  '/admin/users/create': typeof usersPagesCreateRoute
  '/api/admin/import-excel': typeof ApiAdminImportExcelRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/events/$': typeof ApiEventsSplatRoute
  '/api/news/$': typeof ApiNewsSplatRoute
  '/api/opportunities/$': typeof ApiOpportunitiesSplatRoute
  '/api/programs/$': typeof ApiProgramsSplatRoute
  '/api/research/$': typeof ApiResearchSplatRoute
  '/api/stats/$': typeof ApiStatsSplatRoute
  '/api/stories/$': typeof ApiStoriesSplatRoute
  '/admin/events/$eventId/edit': typeof eventsPagesEventIdEditRoute
  '/admin/members/$memberId/edit': typeof membersPagesMemberIdEditRoute
  '/admin/news/$newsId/edit': typeof newsPagesEditRoute
  '/admin/opportunities/$opportunityId/edit': typeof opportunitiesPagesEditRoute
  '/admin/programs/$programId/edit': typeof programsPagesProgramIdEditRoute
  '/admin/research/$researchId/edit': typeof researchPagesResearchIdEditRoute
  '/admin/stories/$storyId/edit': typeof storiesPagesEditRoute
  '/admin/users/$userId/edit': typeof usersPagesUserIdEditRoute
  '/api/auth/admin/$': typeof ApiAuthAdminSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof indexRoute
  '/admin': typeof adminDotrouteRouteWithChildren
  '/auth': typeof authLayoutRouteWithChildren
  '/maintenance': typeof maintenanceRoute
  '/admin/dashboard': typeof dashboardPagesAdminDashboardRoute
  '/admin/events': typeof eventsLayoutRouteWithChildren
  '/admin/members': typeof membersLayoutRouteWithChildren
  '/admin/news': typeof newsLayoutRouteWithChildren
  '/admin/opportunities': typeof opportunitiesLayoutRouteWithChildren
  '/admin/programs': typeof programsLayoutRouteWithChildren
  '/admin/research': typeof researchLayoutRouteWithChildren
  '/admin/stories': typeof storiesLayoutRouteWithChildren
  '/admin/users': typeof usersLayoutRouteWithChildren
  '/api/media': typeof ApiMediaRoute
  '/auth/forgot-password': typeof authPagesForgotPasswordRoute
  '/auth/login': typeof authPagesLoginRoute
  '/auth/reset-password': typeof authPagesResetPasswordRoute
  '/admin/import': typeof importPagesIndexRoute
  '/admin/profile': typeof profilePagesIndexRoute
  '/admin/events/': typeof eventsPagesListRoute
  '/admin/members/': typeof membersPagesListRoute
  '/admin/news/': typeof newsPagesListRoute
  '/admin/opportunities/': typeof opportunitiesPagesListRoute
  '/admin/programs/': typeof programsPagesListRoute
  '/admin/research/': typeof researchPagesListRoute
  '/admin/stories/': typeof storiesPagesListRoute
  '/admin/users/': typeof usersPagesListRoute
  '/admin/events/$eventId': typeof eventsPagesEventIdIndexRoute
  '/admin/events/create': typeof eventsPagesCreateRoute
  '/admin/members/create': typeof membersPagesCreateRoute
  '/admin/news/create': typeof newsPagesCreateRoute
  '/admin/opportunities/create': typeof opportunitiesPagesCreateRoute
  '/admin/programs/create': typeof programsPagesCreateRoute
  '/admin/research/create': typeof researchPagesCreateRoute
  '/admin/stories/create': typeof storiesPagesCreateRoute
  '/admin/users/create': typeof usersPagesCreateRoute
  '/api/admin/import-excel': typeof ApiAdminImportExcelRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/events/$': typeof ApiEventsSplatRoute
  '/api/news/$': typeof ApiNewsSplatRoute
  '/api/opportunities/$': typeof ApiOpportunitiesSplatRoute
  '/api/programs/$': typeof ApiProgramsSplatRoute
  '/api/research/$': typeof ApiResearchSplatRoute
  '/api/stats/$': typeof ApiStatsSplatRoute
  '/api/stories/$': typeof ApiStoriesSplatRoute
  '/admin/events/$eventId/edit': typeof eventsPagesEventIdEditRoute
  '/admin/members/$memberId/edit': typeof membersPagesMemberIdEditRoute
  '/admin/news/$newsId/edit': typeof newsPagesEditRoute
  '/admin/opportunities/$opportunityId/edit': typeof opportunitiesPagesEditRoute
  '/admin/programs/$programId/edit': typeof programsPagesProgramIdEditRoute
  '/admin/research/$researchId/edit': typeof researchPagesResearchIdEditRoute
  '/admin/stories/$storyId/edit': typeof storiesPagesEditRoute
  '/admin/users/$userId/edit': typeof usersPagesUserIdEditRoute
  '/api/auth/admin/$': typeof ApiAuthAdminSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/maintenance'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/members'
    | '/admin/news'
    | '/admin/opportunities'
    | '/admin/programs'
    | '/admin/research'
    | '/admin/stories'
    | '/admin/users'
    | '/api/media'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/admin/import'
    | '/admin/profile'
    | '/admin/events/'
    | '/admin/members/'
    | '/admin/news/'
    | '/admin/opportunities/'
    | '/admin/programs/'
    | '/admin/research/'
    | '/admin/stories/'
    | '/admin/users/'
    | '/admin/events/$eventId'
    | '/admin/events/create'
    | '/admin/members/create'
    | '/admin/news/create'
    | '/admin/opportunities/create'
    | '/admin/programs/create'
    | '/admin/research/create'
    | '/admin/stories/create'
    | '/admin/users/create'
    | '/api/admin/import-excel'
    | '/api/auth/$'
    | '/api/events/$'
    | '/api/news/$'
    | '/api/opportunities/$'
    | '/api/programs/$'
    | '/api/research/$'
    | '/api/stats/$'
    | '/api/stories/$'
    | '/admin/events/$eventId/edit'
    | '/admin/members/$memberId/edit'
    | '/admin/news/$newsId/edit'
    | '/admin/opportunities/$opportunityId/edit'
    | '/admin/programs/$programId/edit'
    | '/admin/research/$researchId/edit'
    | '/admin/stories/$storyId/edit'
    | '/admin/users/$userId/edit'
    | '/api/auth/admin/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/maintenance'
    | '/admin/dashboard'
    | '/api/media'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/admin/import'
    | '/admin/profile'
    | '/admin/events'
    | '/admin/members'
    | '/admin/news'
    | '/admin/opportunities'
    | '/admin/programs'
    | '/admin/research'
    | '/admin/stories'
    | '/admin/users'
    | '/admin/events/$eventId'
    | '/admin/events/create'
    | '/admin/members/create'
    | '/admin/news/create'
    | '/admin/opportunities/create'
    | '/admin/programs/create'
    | '/admin/research/create'
    | '/admin/stories/create'
    | '/admin/users/create'
    | '/api/admin/import-excel'
    | '/api/auth/$'
    | '/api/events/$'
    | '/api/news/$'
    | '/api/opportunities/$'
    | '/api/programs/$'
    | '/api/research/$'
    | '/api/stats/$'
    | '/api/stories/$'
    | '/admin/events/$eventId/edit'
    | '/admin/members/$memberId/edit'
    | '/admin/news/$newsId/edit'
    | '/admin/opportunities/$opportunityId/edit'
    | '/admin/programs/$programId/edit'
    | '/admin/research/$researchId/edit'
    | '/admin/stories/$storyId/edit'
    | '/admin/users/$userId/edit'
    | '/api/auth/admin/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/maintenance'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/members'
    | '/admin/news'
    | '/admin/opportunities'
    | '/admin/programs'
    | '/admin/research'
    | '/admin/stories'
    | '/admin/users'
    | '/api/media'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/admin/import'
    | '/admin/profile'
    | '/admin/events/'
    | '/admin/members/'
    | '/admin/news/'
    | '/admin/opportunities/'
    | '/admin/programs/'
    | '/admin/research/'
    | '/admin/stories/'
    | '/admin/users/'
    | '/admin/events/$eventId'
    | '/admin/events/create'
    | '/admin/members/create'
    | '/admin/news/create'
    | '/admin/opportunities/create'
    | '/admin/programs/create'
    | '/admin/research/create'
    | '/admin/stories/create'
    | '/admin/users/create'
    | '/api/admin/import-excel'
    | '/api/auth/$'
    | '/api/events/$'
    | '/api/news/$'
    | '/api/opportunities/$'
    | '/api/programs/$'
    | '/api/research/$'
    | '/api/stats/$'
    | '/api/stories/$'
    | '/admin/events/$eventId/edit'
    | '/admin/members/$memberId/edit'
    | '/admin/news/$newsId/edit'
    | '/admin/opportunities/$opportunityId/edit'
    | '/admin/programs/$programId/edit'
    | '/admin/research/$researchId/edit'
    | '/admin/stories/$storyId/edit'
    | '/admin/users/$userId/edit'
    | '/api/auth/admin/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute
  adminDotrouteRoute: typeof adminDotrouteRouteWithChildren
  authLayoutRoute: typeof authLayoutRouteWithChildren
  maintenanceRoute: typeof maintenanceRoute
  ApiMediaRoute: typeof ApiMediaRoute
  ApiAdminImportExcelRoute: typeof ApiAdminImportExcelRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiEventsSplatRoute: typeof ApiEventsSplatRoute
  ApiNewsSplatRoute: typeof ApiNewsSplatRoute
  ApiOpportunitiesSplatRoute: typeof ApiOpportunitiesSplatRoute
  ApiProgramsSplatRoute: typeof ApiProgramsSplatRoute
  ApiResearchSplatRoute: typeof ApiResearchSplatRoute
  ApiStatsSplatRoute: typeof ApiStatsSplatRoute
  ApiStoriesSplatRoute: typeof ApiStoriesSplatRoute
  ApiAuthAdminSplatRoute: typeof ApiAuthAdminSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof maintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof adminDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof profilePagesIndexRouteImport
      parentRoute: typeof adminDotrouteRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof importPagesIndexRouteImport
      parentRoute: typeof adminDotrouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof authPagesResetPasswordRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof authPagesLoginRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof authPagesForgotPasswordRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof usersLayoutRouteImport
      parentRoute: typeof adminDotrouteRoute
    }
    '/admin/stories': {
      id: '/admin/stories'
      path: '/stories'
      fullPath: '/admin/stories'
      preLoaderRoute: typeof storiesLayoutRouteImport
      parentRoute: typeof adminDotrouteRoute
    }
    '/admin/research': {
      id: '/admin/research'
      path: '/research'
      fullPath: '/admin/research'
      preLoaderRoute: typeof researchLayoutRouteImport
      parentRoute: typeof adminDotrouteRoute
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof programsLayoutRouteImport
      parentRoute: typeof adminDotrouteRoute
    }
    '/admin/opportunities': {
      id: '/admin/opportunities'
      path: '/opportunities'
      fullPath: '/admin/opportunities'
      preLoaderRoute: typeof opportunitiesLayoutRouteImport
      parentRoute: typeof adminDotrouteRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof newsLayoutRouteImport
      parentRoute: typeof adminDotrouteRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof membersLayoutRouteImport
      parentRoute: typeof adminDotrouteRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof eventsLayoutRouteImport
      parentRoute: typeof adminDotrouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof dashboardPagesAdminDashboardRouteImport
      parentRoute: typeof adminDotrouteRoute
    }
    '/api/stories/$': {
      id: '/api/stories/$'
      path: '/api/stories/$'
      fullPath: '/api/stories/$'
      preLoaderRoute: typeof ApiStoriesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats/$': {
      id: '/api/stats/$'
      path: '/api/stats/$'
      fullPath: '/api/stats/$'
      preLoaderRoute: typeof ApiStatsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research/$': {
      id: '/api/research/$'
      path: '/api/research/$'
      fullPath: '/api/research/$'
      preLoaderRoute: typeof ApiResearchSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/programs/$': {
      id: '/api/programs/$'
      path: '/api/programs/$'
      fullPath: '/api/programs/$'
      preLoaderRoute: typeof ApiProgramsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/opportunities/$': {
      id: '/api/opportunities/$'
      path: '/api/opportunities/$'
      fullPath: '/api/opportunities/$'
      preLoaderRoute: typeof ApiOpportunitiesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news/$': {
      id: '/api/news/$'
      path: '/api/news/$'
      fullPath: '/api/news/$'
      preLoaderRoute: typeof ApiNewsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/$': {
      id: '/api/events/$'
      path: '/api/events/$'
      fullPath: '/api/events/$'
      preLoaderRoute: typeof ApiEventsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/import-excel': {
      id: '/api/admin/import-excel'
      path: '/api/admin/import-excel'
      fullPath: '/api/admin/import-excel'
      preLoaderRoute: typeof ApiAdminImportExcelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/create': {
      id: '/admin/users/create'
      path: '/create'
      fullPath: '/admin/users/create'
      preLoaderRoute: typeof usersPagesCreateRouteImport
      parentRoute: typeof usersLayoutRoute
    }
    '/admin/stories/create': {
      id: '/admin/stories/create'
      path: '/create'
      fullPath: '/admin/stories/create'
      preLoaderRoute: typeof storiesPagesCreateRouteImport
      parentRoute: typeof storiesLayoutRoute
    }
    '/admin/research/create': {
      id: '/admin/research/create'
      path: '/create'
      fullPath: '/admin/research/create'
      preLoaderRoute: typeof researchPagesCreateRouteImport
      parentRoute: typeof researchLayoutRoute
    }
    '/admin/programs/create': {
      id: '/admin/programs/create'
      path: '/create'
      fullPath: '/admin/programs/create'
      preLoaderRoute: typeof programsPagesCreateRouteImport
      parentRoute: typeof programsLayoutRoute
    }
    '/admin/opportunities/create': {
      id: '/admin/opportunities/create'
      path: '/create'
      fullPath: '/admin/opportunities/create'
      preLoaderRoute: typeof opportunitiesPagesCreateRouteImport
      parentRoute: typeof opportunitiesLayoutRoute
    }
    '/admin/news/create': {
      id: '/admin/news/create'
      path: '/create'
      fullPath: '/admin/news/create'
      preLoaderRoute: typeof newsPagesCreateRouteImport
      parentRoute: typeof newsLayoutRoute
    }
    '/admin/members/create': {
      id: '/admin/members/create'
      path: '/create'
      fullPath: '/admin/members/create'
      preLoaderRoute: typeof membersPagesCreateRouteImport
      parentRoute: typeof membersLayoutRoute
    }
    '/admin/events/create': {
      id: '/admin/events/create'
      path: '/create'
      fullPath: '/admin/events/create'
      preLoaderRoute: typeof eventsPagesCreateRouteImport
      parentRoute: typeof eventsLayoutRoute
    }
    '/admin/events/$eventId': {
      id: '/admin/events/$eventId'
      path: '/$eventId'
      fullPath: '/admin/events/$eventId'
      preLoaderRoute: typeof eventsPagesEventIdIndexRouteImport
      parentRoute: typeof eventsLayoutRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof usersPagesListRouteImport
      parentRoute: typeof usersLayoutRoute
    }
    '/admin/stories/': {
      id: '/admin/stories/'
      path: '/'
      fullPath: '/admin/stories/'
      preLoaderRoute: typeof storiesPagesListRouteImport
      parentRoute: typeof storiesLayoutRoute
    }
    '/admin/research/': {
      id: '/admin/research/'
      path: '/'
      fullPath: '/admin/research/'
      preLoaderRoute: typeof researchPagesListRouteImport
      parentRoute: typeof researchLayoutRoute
    }
    '/admin/programs/': {
      id: '/admin/programs/'
      path: '/'
      fullPath: '/admin/programs/'
      preLoaderRoute: typeof programsPagesListRouteImport
      parentRoute: typeof programsLayoutRoute
    }
    '/admin/opportunities/': {
      id: '/admin/opportunities/'
      path: '/'
      fullPath: '/admin/opportunities/'
      preLoaderRoute: typeof opportunitiesPagesListRouteImport
      parentRoute: typeof opportunitiesLayoutRoute
    }
    '/admin/news/': {
      id: '/admin/news/'
      path: '/'
      fullPath: '/admin/news/'
      preLoaderRoute: typeof newsPagesListRouteImport
      parentRoute: typeof newsLayoutRoute
    }
    '/admin/members/': {
      id: '/admin/members/'
      path: '/'
      fullPath: '/admin/members/'
      preLoaderRoute: typeof membersPagesListRouteImport
      parentRoute: typeof membersLayoutRoute
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof eventsPagesListRouteImport
      parentRoute: typeof eventsLayoutRoute
    }
    '/api/auth/admin/$': {
      id: '/api/auth/admin/$'
      path: '/api/auth/admin/$'
      fullPath: '/api/auth/admin/$'
      preLoaderRoute: typeof ApiAuthAdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId/edit': {
      id: '/admin/users/$userId/edit'
      path: '/$userId/edit'
      fullPath: '/admin/users/$userId/edit'
      preLoaderRoute: typeof usersPagesUserIdEditRouteImport
      parentRoute: typeof usersLayoutRoute
    }
    '/admin/stories/$storyId/edit': {
      id: '/admin/stories/$storyId/edit'
      path: '/$storyId/edit'
      fullPath: '/admin/stories/$storyId/edit'
      preLoaderRoute: typeof storiesPagesEditRouteImport
      parentRoute: typeof storiesLayoutRoute
    }
    '/admin/research/$researchId/edit': {
      id: '/admin/research/$researchId/edit'
      path: '/$researchId/edit'
      fullPath: '/admin/research/$researchId/edit'
      preLoaderRoute: typeof researchPagesResearchIdEditRouteImport
      parentRoute: typeof researchLayoutRoute
    }
    '/admin/programs/$programId/edit': {
      id: '/admin/programs/$programId/edit'
      path: '/$programId/edit'
      fullPath: '/admin/programs/$programId/edit'
      preLoaderRoute: typeof programsPagesProgramIdEditRouteImport
      parentRoute: typeof programsLayoutRoute
    }
    '/admin/opportunities/$opportunityId/edit': {
      id: '/admin/opportunities/$opportunityId/edit'
      path: '/$opportunityId/edit'
      fullPath: '/admin/opportunities/$opportunityId/edit'
      preLoaderRoute: typeof opportunitiesPagesEditRouteImport
      parentRoute: typeof opportunitiesLayoutRoute
    }
    '/admin/news/$newsId/edit': {
      id: '/admin/news/$newsId/edit'
      path: '/$newsId/edit'
      fullPath: '/admin/news/$newsId/edit'
      preLoaderRoute: typeof newsPagesEditRouteImport
      parentRoute: typeof newsLayoutRoute
    }
    '/admin/members/$memberId/edit': {
      id: '/admin/members/$memberId/edit'
      path: '/$memberId/edit'
      fullPath: '/admin/members/$memberId/edit'
      preLoaderRoute: typeof membersPagesMemberIdEditRouteImport
      parentRoute: typeof membersLayoutRoute
    }
    '/admin/events/$eventId/edit': {
      id: '/admin/events/$eventId/edit'
      path: '/$eventId/edit'
      fullPath: '/admin/events/$eventId/edit'
      preLoaderRoute: typeof eventsPagesEventIdEditRouteImport
      parentRoute: typeof eventsLayoutRoute
    }
  }
}

interface eventsLayoutRouteChildren {
  eventsPagesListRoute: typeof eventsPagesListRoute
  eventsPagesEventIdIndexRoute: typeof eventsPagesEventIdIndexRoute
  eventsPagesCreateRoute: typeof eventsPagesCreateRoute
  eventsPagesEventIdEditRoute: typeof eventsPagesEventIdEditRoute
}

const eventsLayoutRouteChildren: eventsLayoutRouteChildren = {
  eventsPagesListRoute: eventsPagesListRoute,
  eventsPagesEventIdIndexRoute: eventsPagesEventIdIndexRoute,
  eventsPagesCreateRoute: eventsPagesCreateRoute,
  eventsPagesEventIdEditRoute: eventsPagesEventIdEditRoute,
}

const eventsLayoutRouteWithChildren = eventsLayoutRoute._addFileChildren(
  eventsLayoutRouteChildren,
)

interface membersLayoutRouteChildren {
  membersPagesListRoute: typeof membersPagesListRoute
  membersPagesCreateRoute: typeof membersPagesCreateRoute
  membersPagesMemberIdEditRoute: typeof membersPagesMemberIdEditRoute
}

const membersLayoutRouteChildren: membersLayoutRouteChildren = {
  membersPagesListRoute: membersPagesListRoute,
  membersPagesCreateRoute: membersPagesCreateRoute,
  membersPagesMemberIdEditRoute: membersPagesMemberIdEditRoute,
}

const membersLayoutRouteWithChildren = membersLayoutRoute._addFileChildren(
  membersLayoutRouteChildren,
)

interface newsLayoutRouteChildren {
  newsPagesListRoute: typeof newsPagesListRoute
  newsPagesCreateRoute: typeof newsPagesCreateRoute
  newsPagesEditRoute: typeof newsPagesEditRoute
}

const newsLayoutRouteChildren: newsLayoutRouteChildren = {
  newsPagesListRoute: newsPagesListRoute,
  newsPagesCreateRoute: newsPagesCreateRoute,
  newsPagesEditRoute: newsPagesEditRoute,
}

const newsLayoutRouteWithChildren = newsLayoutRoute._addFileChildren(
  newsLayoutRouteChildren,
)

interface opportunitiesLayoutRouteChildren {
  opportunitiesPagesListRoute: typeof opportunitiesPagesListRoute
  opportunitiesPagesCreateRoute: typeof opportunitiesPagesCreateRoute
  opportunitiesPagesEditRoute: typeof opportunitiesPagesEditRoute
}

const opportunitiesLayoutRouteChildren: opportunitiesLayoutRouteChildren = {
  opportunitiesPagesListRoute: opportunitiesPagesListRoute,
  opportunitiesPagesCreateRoute: opportunitiesPagesCreateRoute,
  opportunitiesPagesEditRoute: opportunitiesPagesEditRoute,
}

const opportunitiesLayoutRouteWithChildren =
  opportunitiesLayoutRoute._addFileChildren(opportunitiesLayoutRouteChildren)

interface programsLayoutRouteChildren {
  programsPagesListRoute: typeof programsPagesListRoute
  programsPagesCreateRoute: typeof programsPagesCreateRoute
  programsPagesProgramIdEditRoute: typeof programsPagesProgramIdEditRoute
}

const programsLayoutRouteChildren: programsLayoutRouteChildren = {
  programsPagesListRoute: programsPagesListRoute,
  programsPagesCreateRoute: programsPagesCreateRoute,
  programsPagesProgramIdEditRoute: programsPagesProgramIdEditRoute,
}

const programsLayoutRouteWithChildren = programsLayoutRoute._addFileChildren(
  programsLayoutRouteChildren,
)

interface researchLayoutRouteChildren {
  researchPagesListRoute: typeof researchPagesListRoute
  researchPagesCreateRoute: typeof researchPagesCreateRoute
  researchPagesResearchIdEditRoute: typeof researchPagesResearchIdEditRoute
}

const researchLayoutRouteChildren: researchLayoutRouteChildren = {
  researchPagesListRoute: researchPagesListRoute,
  researchPagesCreateRoute: researchPagesCreateRoute,
  researchPagesResearchIdEditRoute: researchPagesResearchIdEditRoute,
}

const researchLayoutRouteWithChildren = researchLayoutRoute._addFileChildren(
  researchLayoutRouteChildren,
)

interface storiesLayoutRouteChildren {
  storiesPagesListRoute: typeof storiesPagesListRoute
  storiesPagesCreateRoute: typeof storiesPagesCreateRoute
  storiesPagesEditRoute: typeof storiesPagesEditRoute
}

const storiesLayoutRouteChildren: storiesLayoutRouteChildren = {
  storiesPagesListRoute: storiesPagesListRoute,
  storiesPagesCreateRoute: storiesPagesCreateRoute,
  storiesPagesEditRoute: storiesPagesEditRoute,
}

const storiesLayoutRouteWithChildren = storiesLayoutRoute._addFileChildren(
  storiesLayoutRouteChildren,
)

interface usersLayoutRouteChildren {
  usersPagesListRoute: typeof usersPagesListRoute
  usersPagesCreateRoute: typeof usersPagesCreateRoute
  usersPagesUserIdEditRoute: typeof usersPagesUserIdEditRoute
}

const usersLayoutRouteChildren: usersLayoutRouteChildren = {
  usersPagesListRoute: usersPagesListRoute,
  usersPagesCreateRoute: usersPagesCreateRoute,
  usersPagesUserIdEditRoute: usersPagesUserIdEditRoute,
}

const usersLayoutRouteWithChildren = usersLayoutRoute._addFileChildren(
  usersLayoutRouteChildren,
)

interface adminDotrouteRouteChildren {
  dashboardPagesAdminDashboardRoute: typeof dashboardPagesAdminDashboardRoute
  eventsLayoutRoute: typeof eventsLayoutRouteWithChildren
  membersLayoutRoute: typeof membersLayoutRouteWithChildren
  newsLayoutRoute: typeof newsLayoutRouteWithChildren
  opportunitiesLayoutRoute: typeof opportunitiesLayoutRouteWithChildren
  programsLayoutRoute: typeof programsLayoutRouteWithChildren
  researchLayoutRoute: typeof researchLayoutRouteWithChildren
  storiesLayoutRoute: typeof storiesLayoutRouteWithChildren
  usersLayoutRoute: typeof usersLayoutRouteWithChildren
  importPagesIndexRoute: typeof importPagesIndexRoute
  profilePagesIndexRoute: typeof profilePagesIndexRoute
}

const adminDotrouteRouteChildren: adminDotrouteRouteChildren = {
  dashboardPagesAdminDashboardRoute: dashboardPagesAdminDashboardRoute,
  eventsLayoutRoute: eventsLayoutRouteWithChildren,
  membersLayoutRoute: membersLayoutRouteWithChildren,
  newsLayoutRoute: newsLayoutRouteWithChildren,
  opportunitiesLayoutRoute: opportunitiesLayoutRouteWithChildren,
  programsLayoutRoute: programsLayoutRouteWithChildren,
  researchLayoutRoute: researchLayoutRouteWithChildren,
  storiesLayoutRoute: storiesLayoutRouteWithChildren,
  usersLayoutRoute: usersLayoutRouteWithChildren,
  importPagesIndexRoute: importPagesIndexRoute,
  profilePagesIndexRoute: profilePagesIndexRoute,
}

const adminDotrouteRouteWithChildren = adminDotrouteRoute._addFileChildren(
  adminDotrouteRouteChildren,
)

interface authLayoutRouteChildren {
  authPagesForgotPasswordRoute: typeof authPagesForgotPasswordRoute
  authPagesLoginRoute: typeof authPagesLoginRoute
  authPagesResetPasswordRoute: typeof authPagesResetPasswordRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authPagesForgotPasswordRoute: authPagesForgotPasswordRoute,
  authPagesLoginRoute: authPagesLoginRoute,
  authPagesResetPasswordRoute: authPagesResetPasswordRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  adminDotrouteRoute: adminDotrouteRouteWithChildren,
  authLayoutRoute: authLayoutRouteWithChildren,
  maintenanceRoute: maintenanceRoute,
  ApiMediaRoute: ApiMediaRoute,
  ApiAdminImportExcelRoute: ApiAdminImportExcelRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiEventsSplatRoute: ApiEventsSplatRoute,
  ApiNewsSplatRoute: ApiNewsSplatRoute,
  ApiOpportunitiesSplatRoute: ApiOpportunitiesSplatRoute,
  ApiProgramsSplatRoute: ApiProgramsSplatRoute,
  ApiResearchSplatRoute: ApiResearchSplatRoute,
  ApiStatsSplatRoute: ApiStatsSplatRoute,
  ApiStoriesSplatRoute: ApiStoriesSplatRoute,
  ApiAuthAdminSplatRoute: ApiAuthAdminSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
