/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as maintenanceRouteImport } from './app/maintenance'
import { Route as authLayoutRouteImport } from './app/auth/layout'
import { Route as adminDotrouteRouteImport } from './app/admin.route'
import { Route as indexRouteImport } from './app/index'
import { Route as authPagesLoginRouteImport } from './app/auth/pages/login'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$'
import { Route as ApiAuthAdminSplatRouteImport } from './app/api/auth/admin/$'

const maintenanceRoute = maintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const adminDotrouteRoute = adminDotrouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authPagesLoginRoute = authPagesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authLayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAdminSplatRoute = ApiAuthAdminSplatRouteImport.update({
  id: '/api/auth/admin/$',
  path: '/api/auth/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof indexRoute
  '/admin': typeof adminDotrouteRoute
  '/auth': typeof authLayoutRouteWithChildren
  '/maintenance': typeof maintenanceRoute
  '/auth/login': typeof authPagesLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/admin/$': typeof ApiAuthAdminSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof indexRoute
  '/admin': typeof adminDotrouteRoute
  '/auth': typeof authLayoutRouteWithChildren
  '/maintenance': typeof maintenanceRoute
  '/auth/login': typeof authPagesLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/admin/$': typeof ApiAuthAdminSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof indexRoute
  '/admin': typeof adminDotrouteRoute
  '/auth': typeof authLayoutRouteWithChildren
  '/maintenance': typeof maintenanceRoute
  '/auth/login': typeof authPagesLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/admin/$': typeof ApiAuthAdminSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/maintenance'
    | '/auth/login'
    | '/api/auth/$'
    | '/api/auth/admin/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/maintenance'
    | '/auth/login'
    | '/api/auth/$'
    | '/api/auth/admin/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/maintenance'
    | '/auth/login'
    | '/api/auth/$'
    | '/api/auth/admin/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute
  adminDotrouteRoute: typeof adminDotrouteRoute
  authLayoutRoute: typeof authLayoutRouteWithChildren
  maintenanceRoute: typeof maintenanceRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthAdminSplatRoute: typeof ApiAuthAdminSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof maintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof adminDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof authPagesLoginRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/admin/$': {
      id: '/api/auth/admin/$'
      path: '/api/auth/admin/$'
      fullPath: '/api/auth/admin/$'
      preLoaderRoute: typeof ApiAuthAdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authLayoutRouteChildren {
  authPagesLoginRoute: typeof authPagesLoginRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authPagesLoginRoute: authPagesLoginRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  adminDotrouteRoute: adminDotrouteRoute,
  authLayoutRoute: authLayoutRouteWithChildren,
  maintenanceRoute: maintenanceRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthAdminSplatRoute: ApiAuthAdminSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
